### PR TITLE
Support grape param arrays of primitives

### PR DESCRIPTION
**Pull request by jhollinger**
Fixes issue #30

### CODE REVIEW

**Comment by jhollinger** [comment]
Also adds support for using a `Proc` as a default param value:

    params do
      optional :foo, default: -> { 'Foo' }
    end

**Comment by rngtng** [comment]
was this closed on purpose?

**Comment by jhollinger** [comment]
Yes, it appears to have been fixed by another commit in master.

**Comment by rngtng** [comment]
ah ok :+1:

**Pull request closed without merging**
